# gateway-dist.leonzhangxf.com
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: gateway-dist.leonzhangxf.com
  namespace: {{ NAMESPACE }}
spec:
  selector:
    matchLabels:
      name: gateway-dist.leonzhangxf.com
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway-dist.leonzhangxf.com
    spec:
      containers:
        - name: gateway-dist.leonzhangxf.com
          image: {{ REGISTRY }}/gateway-dist.leonzhangxf.com:{{ TAG }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 1

---

# Service
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: gateway-dist.leonzhangxf.com
  namespace: {{ NAMESPACE }}
spec:
  selector:
    name: gateway-dist.leonzhangxf.com
  type: NodePort
  ports:
    - name: http
      nodePort: 30001
      port: 8080

---

# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-dist.leonzhangxf.com
  namespace: {{ NAMESPACE }}
data:
  application.yaml: |-
    gateway:
      config:
        message: maggie
    ---
    spring:
      profiles: dev
    gateway:
      config:
        message: leon&maggie