# account-dist.leonzhangxf.com
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: account-dist.leonzhangxf.com
  namespace: {{ NAMESPACE }}
spec:
  selector:
    matchLabels:
      name: account-dist.leonzhangxf.com
  replicas: 1
  template:
    metadata:
      labels:
        name: account-dist.leonzhangxf.com
    spec:
      containers:
        - name: account-dist.leonzhangxf.com
          image: {{ REGISTRY }}/account-dist.leonzhangxf.com:{{ TAG }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 1

---

# Service
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: account-dist.leonzhangxf.com
  namespace: {{ NAMESPACE }}
spec:
  selector:
    name: account-dist.leonzhangxf.com
  ports:
    - name: http
      port: 8080